<a href="https://colab.research.google.com/github/YuansongFeng/MadMario/blob/master/numpy_torch_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###    Get familiar with torch.tensor:

1. To create a tensor

In [ ]:
import torch
import torch.tensor as tensor
t = tensor([[1,2,3],[8,9,4],[7,6,5]])
t

tensor([[1, 2, 3],
        [8, 9, 4],
        [7, 6, 5]])

2. To get element at 1st row, 2nd col:

In [ ]:
t[0,1]


tensor(2)

3. To get elements at (1st row, 2nd col) and (3rd row, 1st col):

In [ ]:
t[[0,2],[1,0]]

tensor([2, 7])

4. To get the largest number:

In [ ]:
torch.max(t)

tensor(9)

5. To get largest values and corresponding indices along 1st axis:

In [ ]:
torch.max(t, axis = 0)

torch.return_types.max(values=tensor([8, 9, 5]), indices=tensor([1, 1, 2]))


> Note: From the example above, you can see torch.max return a *namedtuple (values, indices)*, where *values* contains the maximum number along the given axis. And *indices* contain the indices location of each maximum value found (argmax). Thus, you do not need a different function to get the argmax.




6. To get largest values along 1st axis:

In [ ]:
torch.max(t, axis = 0)[0]

tensor([8, 9, 5])

7. To get indices of largest values along 1st axis:

In [ ]:
torch.max(t, axis = 0)[1]

tensor([1, 1, 2])

8. To convert torch.tensor to NumPy array:

In [ ]:
t.numpy()

array([[1, 2, 3],
       [8, 9, 4],
       [7, 6, 5]])

###    Get familiar with NumPy

1. Create a numpy array:

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[8,9,4],[7,6,5]])
arr

array([[1, 2, 3],
       [8, 9, 4],
       [7, 6, 5]])

2. To get element at 1st row, 2nd col:

In [ ]:
arr[0,1]

2

3. To get elements at (1st row, 2nd col) and (3rd row, 1st col):

In [ ]:
arr[[0,2],[1,0]]

array([2, 7])

4. To get max numbers in a along 1st axis:

In [ ]:
np.max(arr, axis = 0)

array([8, 9, 5])

5. To get the indices of max numbers in a along 1st axis:

In [ ]:
np.argmax(arr, axis=0)

array([1, 1, 2])

Although some people are more comfortable using numpy array, sometimes we should not convert torch.tensor to numpy array, because torch.tensor has an attribute *grad* which keeps track of gradients for the tensor and is used to update our Q function(We will mention this later); converting it to numpy would lose gradient information